embedding_size_enc: 20
embedding_size_dec: 20
hidden_size_enc: 128
hidden_size_dec: 128
num_layers_enc: 1
num_layers_dec: 1

epochs: 50
batch_size: 256

experiment_dir: exps/default/
save_min_epoch: 5 
